name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Path of current directory
        run: pwd

      - name: List All Files
        run: ls -a

      - name: Create .env file
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "LOG_LEVEL=${{secrets.LOG_LEVEL }}" >> .env
          echo "LOGTAIL_TOKEN=${{ secrets.LOGTAIL_TOKEN }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "REDIS_CONNECTION_URL=${{ secrets.REDIS_CONNECTION_URL }}" >> .env
          echo "TEST_WORKING=yes" >> .env

      - name: List All Files
        run: ls -a

      - name: List .env file
        run: cat .env

      - name: Build application
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd
            ls -a
            cd identity-reconcilation
            git pull origin master
            yarn install
            yarn restart
